name       : gamemode
version    : '1.5'
release    : 5
source     :
    - https://github.com/FeralInteractive/gamemode/releases/download/1.5/gamemode-1.5.tar.xz : 262389e0a625670c5f53f89d0c30a28cd5f9569a8e6b012dccf78b7fdcb98408
license    : BSD-3-Clause
component  : games
summary    : Optimise Linux system performance on demand
description: |
    Automatic helper to optimise Linux system performance when gaming
builddeps  :
    - pkgconfig32(dbus-1)
    - pkgconfig32(libgcrypt)
    - pkgconfig32(liblzma)
    - pkgconfig32(libsystemd)
patterns   :
    - /usr/include  # No need to split gamemode-devel just yet.
libsplit   : no
emul32     : yes
setup      : |
    # Only want the two libs for the 32bit build. We'll use these in future
    # with LSI experimentation to help out other non Feral titles.
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        %meson_configure -Dwith-daemon=false -Dwith-pam-group=users
    else
        %meson_configure -Dwith-pam-group=users
    fi
build      : |
    %ninja_build
install    : |
    %ninja_install
    install -Dm00644 example/gamemode.ini $installdir/usr/share/doc/gamemode/gamemode.ini
