name       : gamemode
version    : 1.3.1
release    : 4
source     :
    - https://github.com/FeralInteractive/gamemode/releases/download/1.3.1/gamemode-1.3.1.tar.xz : fa0797ab61c255206ec90eec7d404b760ac92c932b6550296ced8686c532e67e
license    : BSD-3-Clause
component  : games
summary    : Optimise Linux system performance on demand
description: |
    Automatic helper to optimise Linux system performance when gaming
builddeps  :
    - pkgconfig32(libsystemd)
patterns   :
    - /usr/include  # No need to split gamemode-devel just yet.
libsplit   : no
emul32     : yes
setup      : |
    # Only want the two libs for the 32bit build. We'll use these in future
    # with LSI experimentation to help out other non Feral titles.
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        %meson_configure -Dwith-daemon=false -Dwith-pam-group=users
    else
        %meson_configure -Dwith-pam-group=users
    fi
build      : |
    %ninja_build
install    : |
    %ninja_install
    install -Dm00644 example/gamemode.ini $installdir/usr/share/doc/gamemode/gamemode.ini
