name       : gamemode
version    : '1.6'
release    : 7
source     :
    - https://github.com/FeralInteractive/gamemode/releases/download/1.6/gamemode-1.6.tar.xz : 4fec5a0900e8f559b37cf1711ca7dcea7e1cebfe1237ce314001f65c1e346a5d
license    : BSD-3-Clause
component  : games
libsplit   : no
emul32     : yes
summary    : Optimise Linux system performance on demand
description: |
    Automatic helper to optimise Linux system performance when gaming
builddeps  :
    - pkgconfig32(dbus-1)
    - pkgconfig32(libgcrypt)
    - pkgconfig32(liblzma)
    - pkgconfig32(libsystemd)
setup      : |
    %meson_configure -Dwith-pam-group=users
build      : |
    %ninja_build
install    : |
    %ninja_install
    install -Dm00644 example/gamemode.ini $installdir/usr/share/doc/gamemode/gamemode.ini
